### ISSUE TITLE
Scrolling Not Allowed By Default

### ISSUE THREAD

**Issue by freshleafmedia** [pboivin/filament-peek#12]
The README states:

> By default, only scrolling is allowed in the preview iframe.

This appears to not be the case. When `allowIframePointerEvents` config is set to `false` the iframe gets the [`pointer-events: none` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) set which prevents all interaction with the iframe including scrolling.

Tested in FireFox and Chromium.

It appears the only way to get scrolling and nothing else is to add the `pointer-events` declaration to the template as described further on in the README.

**Comment by pboivin** [comment]
Hey @freshleafmedia, thank you for taking the time to report this! I've had mixed results myself, `pointer-events: none` seems to allow scrolling in the iframe most of the time, but not always. I'm thinking of removing the option in the `1.0` release and leaving it to be configured in the preview template. I'll keep testing!

**Comment by freshleafmedia** [comment]
@pboivin Can confirm it's now working as expected :+1:
