### ISSUE TITLE
[v1.1.0] Possible problem in Safari

### ISSUE THREAD

**Issue by lotarbo** [pboivin/filament-peek#78]
Hello, i have admin panel on domain ex: **admin.com** and Next.js project on **front.com**
So i use preview like this https://github.com/pboivin/filament-peek/blob/2.x/docs/page-previews.md#filament-as-headless-cms

in Chrome everything is working, but in Safari i see 404 error with console errors

**Blocked a frame with origin "front.com" from accessing a frame with origin "admin.com". Protocols, domains, and ports must match.**

**SecurityError: Blocked a frame with origin "admin.com" from accessing a cross-origin frame. Protocols, domains, and ports must match.**

Also, open preview link in safari - everything is working again. Only in Preview i have errors

**Comment by pboivin** [comment]
Hey @lotarbo, thank you for reporting this, I'll try to replicate it on my end tomorrow. I'll let you know if I find a solution.

**Comment by lotarbo** [comment]
@pboivin thank you. all i found - recommends using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to communicate between windows

**Comment by pboivin** [comment]
Hey @lotarbo, I just tagged [v1.1.1](https://github.com/pboivin/filament-peek/releases/tag/v1.1.1) with a fix regarding external URLs for previews. When you have some time, can you give this a quick test and let me know if it works for you?

**Comment by lotarbo** [comment]
@pboivin thank you. Right now, i don't have errors in console)
But preview still doesn't work in safari. Next.js project hosted on Netlify and uses default preview code from docs. And i saw, Safari can't install Next.js cookies in iframe, that's why i have 404 error i think.
And right now i dont understand, this is problem with iframe, nextjs or headers from both servers(

**Comment by lotarbo** [comment]
Sorry, i think i found, problem only with safari) https://community.prismic.io/t/troubleshooting-previews/5449#previews-not-working-in-safari-14

**Comment by pboivin** [comment]
Thanks for looking into this! So, does the solution in the page you shared solve the problem for you? I think I'm not able to replicate because I'm not using cookies to handle previews on my projects.

**Comment by lotarbo** [comment]
It helps)
But i have small question: in chrome and safari i can interact with preview frame, but in config i have this
`'allowIframePointerEvents' => false,`, its normal behavior? Because i this option should prevent interaction

**Comment by pboivin** [comment]
Yes, unfortunately this is part of the issue I was trying to solve in `v1.1.1`. `allowIframePointerEvents` will not work with a preview URL because it's trying to inject some CSS into the page. I'll add it to the documentation. A simple solution would be to add some CSS in your preview component:
```html
    <style>
        body.is-preview a { pointer-events: none !important; }
    </style>
```

**Comment by pboivin** [comment]
Thanks @lotarbo
